@api =  http://localhost:8080/api/rutinas


###Get all cuestionarios
GET {{api}}

### Get all cuestionarios
GET http://localhost:8080/api/rutinas


### Get cuestionario by id
GET http://localhost:8080/api/rutina/1


### Create cuestionario 
POST http://localhost:8080/api/rutina
Content-Type: application/json

{
    "dia" : "domingo",
    "IDejercicio": 1,
    "IDusuario": 2
}

### Update cuestionario
PUT http://localhost:8080/api/rutina/1
Content-Type: application/json

{
    "dia" : "domingo",
    "IDejercicio": 1,
    "IDusuario": 1
}

### Delete cuestionario

DELETE http://localhost:8080/api/rutina/2