SELECT [IDalimento]
        ,[nombre]
        ,[descripcion]
        ,[calorias]
        ,[proteinas]
        ,[azucares]
        ,[carbohidratos]
        ,[gramos]
        ,[grasas]
FROM [dbo].[alimento]